name = "SafeTensors"
uuid = "eeda0dda-7046-4914-a807-2495fc7abb89"
authors = ["pevnak <pevnak@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
